version: '3'

services:
  node:
    image: ruiban/node:pm2
    container_name: node
    restart: always
    tty: true
    privileged: true
    #cap_add: 
    #- ALL
    expose:
    - '80'
    - '443'
    volumes:
    - ~/nbn/node/www:/www
    #command: 'node /www/index.js'
    networks:
    - node

networks:
  node:
    external: 
      name: docker
